# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  services:
    postgres:
      image: postgres:12-alpine
      env:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: password
        POSTGRES_DB: root
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5

  test:
    - name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    
    - name: DB creation and migration 
      run: make createdb
      run: make migrateup

    - name: Test
      run: make tests
